name: concourse-discord-webhook-resource
packagePath: .
org: favware
monoRepo: false
tagTemplate: v{{new-version}}
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
githubRepo: auto
githubReleaseNameTemplate: '{{new-version}}'
