services:
  dev:
    image: ghcr.io/favware/concource-discord-webhook-resource:dev
    container_name: concourse-discord-webhook-resource-dev
    build: .
    tty: true
    stdin_open: true
    command: /bin/bash

  taskrunner:
    image: ghcr.io/favware/concource-taskrunner:dev
    build:
      context: .
      dockerfile: Dockerfile.taskrunner
    container_name: taskrunner
    tty: true
    stdin_open: true
    command: /bin/bash
