#!/bin/sh

# The MIT License (MIT)
# Copyright (c) 2017-2020     James Hunt
# Copyright (c) 2021-present  Benjamin Gandon, Gstack
# Retrieved from: https://github.com/cloudfoundry-community/slack-notification-resource/blob/62db24f60f5b442b60d7160edec533662d26c23a/in

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

PAYLOAD=$(mktemp /tmp/resource-in.XXXXXX)

cat > "$PAYLOAD" <&0

TS=$(jq '.version.timestamp // empty' < "$PAYLOAD")
[ -z "$TS" ] && TS='"none"'

jq -n "{
  version: {
    timestamp: $TS
  }
}" >&3
