#!/usr/bin/env sh

# set -e

cd "${1}"

exec 3>&1
exec 1>&2
set +x

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp /tmp/resource-in.XXXXXX)

cat > "${payload}" <&0

echo "Payload: $(cat ${payload})"

timestamp="$(jq -n "{version:{timestamp:\"$(date +%s)\"}}")"

echo "Timestamp: ${timestamp}"

disable="$(jq -r '.source.disable' < "${payload}")"
if [[ "$disable" == "true" ]]
then
    echo "$timestamp" >&3
    exit 0
fi

webhook_url="$(jq -r '.source.url' < "${payload}")"
allow_insecure="$(jq -r '.source.insecure // "false"' < "${payload}")"
proxy="$(jq -r '.source.proxy // "null"' < "${payload}")"

content="$(jq -r '.params.content // ""' < "${payload}")"
username="$(jq '(.params.username // null)' < "${payload}")"
avatar_url="$(jq '(.params.avatar_url // null)' < "${payload}")"
allowed_role_mentions="$(jq '(.params.allowed_mentions.roles // "[]")[]' < "${payload}")"
allowed_user_mentions="$(jq '(.params.allowed_mentions.users // "[]")[]' < "${payload}")"
suppress_embeds="$(jq '(.params.flags.suppress_embeds // "false")' < "${payload}")"
suppress_notifications="$(jq '(.params.flags.suppress_notifications // "false")' < "${payload}")"
verbose="$(jq '(.params.verbose // "false")' < "${payload}")"

echo "webhook_url: ${webhook_url}"
echo "allow_insecure: ${allow_insecure}"
echo "proxy: ${proxy}"
echo "content: ${content}"
echo "username: ${username}"
echo "avatar_url: ${avatar_url}"
echo "allowed_role_mentions: ${allowed_role_mentions}"
echo "allowed_user_mentions: ${allowed_user_mentions}"
echo "suppress_embeds: ${suppress_embeds}"
echo "suppress_notifications: ${suppress_notifications}"
echo "verbose: ${verbose}"
echo "other params: $(jq -r '.params' < "${payload}")"

allowed_role_mentions_options=""

for role in $allowed_role_mentions; do
  allowed_role_mentions_options+="--allowed-role-mentions \"$role\" "
done

allowed_user_mentions_options=""

for user in $allowed_user_mentions; do
  allowed_user_mentions_options+="--allowed-user-mentions \"$user\" "
done

echo "allowed_role_mentions_options: ${$allowed_role_mentions_options}"
echo "allowed_user_mentions_options: ${$allowed_user_mentions_options}"

echo "--------------------------------------------------------------------------------------"

printenv

echo "--------------------------------------------------------------------------------------"

node /usr/src/app/dist/index.js \
    --webhook-url "${webhook_url}" \
    --allow-insecure "${allow_insecure}" \
    --proxy "${proxy}" \
    --content "${content}" \
    --username "${username}" \
    --avatar-url "${avatar_url}" \
    ${$allowed_role_mentions_options} \
    ${$allowed_user_mentions_options} \
    --suppress-embeds "${suppress_embeds}" \
    --suppress-notifications "${suppress_notifications}" \
    --verbose "${verbose}"
