#!/usr/bin/env sh

set -e

cd "${1}"

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging
set +x

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp /tmp/resource-in.XXXXXX)

cat > "${payload}" <&0

timestamp="$(jq -n "{version:{timestamp:\"$(date +%s)\"}}")"

disable="$(jq -r '.source.disable' < "${payload}")"
if [[ "$disable" == "true" ]]
then
    echo "$timestamp" >&3
    exit 0
fi

webhook_url="$(jq -r '.source.url' < "${payload}")"
allow_insecure="$(jq -r '.source.insecure // "false"' < "${payload}")"
proxy="$(jq -r '.source.proxy // "null"' < "${payload}")"

content="$(jq -r '.params.content // ""' < "${payload}")"
username="$(jq '(.params.username // null)' < "${payload}")"
avatar_url="$(jq '(.params.avatar_url // null)' < "${payload}")"
allowed_role_mentions="$(jq '(.params.allowed_mentions.roles // [])' < "${payload}")"
allowed_user_mentions="$(jq '(.params.allowed_mentions.users // [])' < "${payload}")"
suppress_embeds="$(jq '(.params.flags.suppress_embeds // "false")' < "${payload}")"
suppress_notifications="$(jq '(.params.flags.suppress_notifications // "false")' < "${payload}")"
verbose="$(jq '(.params.verbose // "false")' < "${payload}")"

allowed_role_mentions_options=""

allowed_roles_count=$(echo $allowed_role_mentions | jq '. | length')
if [ $allowed_roles_count -gt 0 ]; then
  for i in $(seq 0 $(($allowed_roles_count - 1))); do
    allowed_role_mentions_options="${allowed_role_mentions_options}$(echo "--allowed-role-mentions $(echo $allowed_role_mentions | jq -r ".[$i]") ")"
  done
fi

allowed_user_mentions_options=""

allowed_users_count=$(echo $allowed_user_mentions | jq '. | length')
if [ $allowed_users_count -gt 0 ]; then
  for i in $(seq 0 $(($allowed_users_count - 1))); do
    allowed_user_mentions_options="${allowed_user_mentions_options}$(echo "--allowed-user-mentions $(echo $allowed_user_mentions | jq -r ".[$i]") ")"
  done
fi

node /usr/src/app/dist/index.js \
    --webhook-url ${webhook_url} \
    --allow-insecure ${allow_insecure} \
    --proxy ${proxy} \
    --content ${content} \
    --username ${username} \
    --avatar-url ${avatar_url} \
    ${allowed_role_mentions_options} \
    ${allowed_user_mentions_options} \
    --suppress-embeds ${suppress_embeds} \
    --suppress-notifications ${suppress_notifications} \
    --verbose ${verbose}

echo "$timestamp" | jq -s add >&3
